/**
 * Generate a Markdown document from NotesData + VideoInfo.
 */
export function generateMarkdown(notes, video) {
  const lines = [];

  lines.push(`# ${notes.title || video.title}`);
  lines.push('');
  if (video.channel) lines.push(`> **Channel:** ${video.channel}`);
  if (video.duration) lines.push(`> **Duration:** ${video.duration}`);
  lines.push(`> **Source:** ${video.url}`);
  lines.push(`> *Generated by [NoteTube](https://github.com/notetube)*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(notes.summary || '_No summary available._');
  lines.push('');

  // Detailed Notes
  if (notes.detailed_notes?.length) {
    lines.push('## Detailed Notes');
    lines.push('');
    notes.detailed_notes.forEach((section) => {
      lines.push(`### ${section.heading}`);
      lines.push('');
      lines.push(section.content);
      lines.push('');
    });
  }

  // Key Concepts
  if (notes.key_concepts?.length) {
    lines.push('## Key Concepts');
    lines.push('');
    notes.key_concepts.forEach((c) => {
      lines.push(`### ${c.name}`);
      lines.push('');
      lines.push(c.explanation);
      if (c.example) {
        lines.push('');
        lines.push(`> **Example:** ${c.example}`);
      }
      lines.push('');
    });
  }

  // Important Points
  if (notes.important_points?.length) {
    lines.push('## Important Points');
    lines.push('');
    notes.important_points.forEach((p) => lines.push(`- ${p}`));
    lines.push('');
  }

  // Examples
  if (notes.examples?.length) {
    lines.push('## Examples');
    lines.push('');
    notes.examples.forEach((e, i) => lines.push(`${i + 1}. ${e}`));
    lines.push('');
  }

  // Flashcards
  if (notes.flashcards?.length) {
    lines.push('## Flashcards');
    lines.push('');
    notes.flashcards.forEach((card, i) => {
      lines.push(`### Q${i + 1}: ${card.question}`);
      lines.push('');
      lines.push(`**Answer:** ${card.answer}`);
      lines.push('');
    });
  }

  // Quiz
  if (notes.quiz?.length) {
    lines.push('## Quiz');
    lines.push('');
    notes.quiz.forEach((q, i) => {
      lines.push(`### Q${i + 1}: ${q.question}`);
      lines.push('');
      q.options.forEach((opt) => lines.push(`- ${opt}`));
      lines.push('');
      lines.push(`**Answer:** ${q.correct_answer}`);
      lines.push('');
      lines.push(`*${q.explanation}*`);
      lines.push('');
    });
  }

  return lines.join('\n');
}

export function downloadMarkdown(content, filename = 'notes.md') {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
